### ISSUE TITLE
Selamat datang

### ISSUE THREAD

**Issue by tonidy** [smkmhs/home#1]
Halo all,

Terima kasih buat teman-teman yang sudah menerima undangan untuk mendaftar di Github. Saya lihat ada 3 orang dari 3 kelompok yang sudah mendaftar, yaitu:
- @Frozy12 dari kelompok 1
- @aslam200 dari kelompok 2
- @leyonard dari kelompok 3

Untuk kelompok 3 dan 4, saya minta tolong @Frozy12 untuk kasih tahu ke kelompok 4 yang emailnya:
- angelabatam{at]gmail.com
- tinekewinokan1[at]gmail.com

@Frozy12 tolong bantu mereka berdua ya.
## Untuk semua kelompok
1. Masing-masing anggota mendaftar di Github ya -> ini linknya https://github.com/join?source=header
2. Lalu tolong buatkan list username anggotanya dan disalin melalui komentar di bawah ini.

_Note_: Kalau ada yang kurang mengerti silakan bertanya di sini ya.

cc: @tuxkeren

**Comment by tonidy** [comment]
Hi @aslam200, @leyonard , @Frozy12,

Kalian dapet pesan di atas kan? Kalau dapet, tolong komentar di bawah. Terima kasih

**Comment by Frozy12** [comment]
Sudah pak (y)

**Comment by tonidy** [comment]
@Frozy12 terima kasih. Yang lainnya mana? Kok belum pada daftar di Github. Tolong senggol yang lainnya ya :dancer:

**Comment by aslam200** [comment]
Sudah pak
hi semuanya

**Comment by tonidy** [comment]
mantap :+1: @aslam200 . Tolong ajakin teman-teman sekelas buat gabung di sini ya. Link login di sini https://github.com/join?source=header

**Comment by tuxkeren** [comment]
trus bagai mana lagi...?

**Comment by leyonard** [comment]
2016-08-29 10:49 GMT+07:00 Athailah notifications@github.com:

**Comment by tonidy** [comment]
Masih belum pada daftar nih, yang daftar baru 4 orang

![image](https://cloud.githubusercontent.com/assets/823034/18119729/3b76633a-6f86-11e6-94c0-e28c277f9fe8.png)

Di atas saya sudah bilang ya, untuk semua siswa segera mendaftar di github.

# Untuk semua kelompok
- Masing-masing anggota mendaftar di Github ya -> ini linknya https://github.com/join?source=header
- Lalu tolong buatkan list username anggotanya dan disalin melalui komentar di bawah ini.

**Comment by Frozy12** [comment]
nnti sy ingatkan lagi pak

**Comment by tonidy** [comment]
Siip :+1: , thanks ya @Frozy12

**Comment by tonidy** [comment]
@Frozy12  sudah diingatkan belum ya? Anggota di github masih belum nambah nih :smile: . Pada kemana ini orang-orangnya?

**Comment by aslam200** [comment]
@MrHeri ( https://github.com/MrHeri ) member dari kelompok 4 pak tolong
invite pak 😁

**Comment by aslam200** [comment]
@andikusnaidi (https://github.com/andikusnaidi) member dari kelompok 5 , Invite ya pak @tonidy

**Comment by tonidy** [comment]
@aslam200 oke, sudah saya invite. Baru 2 orang nih :smile:, yang lainnya mana?

**Comment by aslam200** [comment]
@eqwinmanurung kelompok 3 pak tolong diinvite yaa

**Comment by aslam200** [comment]
@Eqwinmanurung

**Comment by Svz1404** [comment]
@Svz1404 Kelompok 4

**Comment by arasma100** [comment]
Kelompok 4
@arasma100

**Comment by dennysetiawan** [comment]
@dennysetiawan kelompok 3

**Comment by asaputra1** [comment]
kelompok 1
@asaputra1

**Comment by AgustianSubakti** [comment]
@AgustianSubakti Kelompok 4

**Comment by Light992** [comment]
dari kelompok 4
@Light992

**Comment by rokipdj88** [comment]
@rokipdj88
Kelompok 4

**Comment by jihankhairunnisa** [comment]
@jihankhairunnisa kelompok 1

**Comment by sherlydwic** [comment]
@sherlydwic kelompok 3

**Comment by leyonard** [comment]
kelompok 4 masta semua

**Comment by melinia** [comment]
test

**Comment by melinia** [comment]
@melinia kelompok 2
